# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1069, 846)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabWidget.sizePolicy().hasHeightForWidth())
        self.tabWidget.setSizePolicy(sizePolicy)
        self.tabWidget.setMinimumSize(QtCore.QSize(600, 600))
        self.tabWidget.setObjectName("tabWidget")
        self.tab_controls = QtWidgets.QWidget()
        self.tab_controls.setObjectName("tab_controls")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.tab_controls)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.groupBox = QtWidgets.QGroupBox(self.tab_controls)
        self.groupBox.setMaximumSize(QtCore.QSize(16777215, 100))
        self.groupBox.setObjectName("groupBox")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.groupBox)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.ipEdit = QtWidgets.QLineEdit(self.groupBox)
        self.ipEdit.setMaximumSize(QtCore.QSize(200, 16777215))
        self.ipEdit.setObjectName("ipEdit")
        self.horizontalLayout.addWidget(self.ipEdit)
        self.portLabel = QtWidgets.QLabel(self.groupBox)
        self.portLabel.setObjectName("portLabel")
        self.horizontalLayout.addWidget(self.portLabel)
        self.portEdit = QtWidgets.QLineEdit(self.groupBox)
        self.portEdit.setMaximumSize(QtCore.QSize(100, 16777215))
        self.portEdit.setObjectName("portEdit")
        self.horizontalLayout.addWidget(self.portEdit)
        self.connectButton = QtWidgets.QPushButton(self.groupBox)
        self.connectButton.setObjectName("connectButton")
        self.horizontalLayout.addWidget(self.connectButton)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.verticalLayout_2.addWidget(self.groupBox)
        self.groupBox_4 = QtWidgets.QGroupBox(self.tab_controls)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_4.sizePolicy().hasHeightForWidth())
        self.groupBox_4.setSizePolicy(sizePolicy)
        self.groupBox_4.setMinimumSize(QtCore.QSize(0, 200))
        self.groupBox_4.setMaximumSize(QtCore.QSize(16777215, 200))
        self.groupBox_4.setObjectName("groupBox_4")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.groupBox_4)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.selectFolderBtn = QtWidgets.QPushButton(self.groupBox_4)
        self.selectFolderBtn.setObjectName("selectFolderBtn")
        self.gridLayout.addWidget(self.selectFolderBtn, 0, 0, 1, 1)
        self.folderLabel = QtWidgets.QLabel(self.groupBox_4)
        self.folderLabel.setObjectName("folderLabel")
        self.gridLayout.addWidget(self.folderLabel, 0, 1, 1, 3)
        self.initBtn = QtWidgets.QPushButton(self.groupBox_4)
        self.initBtn.setObjectName("initBtn")
        self.gridLayout.addWidget(self.initBtn, 1, 0, 1, 1)
        self.readStatBtn = QtWidgets.QPushButton(self.groupBox_4)
        self.readStatBtn.setObjectName("readStatBtn")
        self.gridLayout.addWidget(self.readStatBtn, 1, 1, 1, 1)
        self.lastCmdBtn = QtWidgets.QPushButton(self.groupBox_4)
        self.lastCmdBtn.setObjectName("lastCmdBtn")
        self.gridLayout.addWidget(self.lastCmdBtn, 1, 2, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(612, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem1, 1, 3, 1, 1)
        self.verticalLayout_3.addLayout(self.gridLayout)
        self.verticalLayout_2.addWidget(self.groupBox_4)
        self.label_3 = QtWidgets.QLabel(self.tab_controls)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_2.addWidget(self.label_3)
        self.textBrowser = QtWidgets.QTextBrowser(self.tab_controls)
        self.textBrowser.setObjectName("textBrowser")
        self.verticalLayout_2.addWidget(self.textBrowser)
        self.statusLabel = QtWidgets.QLabel(self.tab_controls)
        self.statusLabel.setText("")
        self.statusLabel.setObjectName("statusLabel")
        self.verticalLayout_2.addWidget(self.statusLabel)
        self.tabWidget.addTab(self.tab_controls, "")
        self.tabHousekeeping = QtWidgets.QWidget()
        self.tabHousekeeping.setObjectName("tabHousekeeping")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.tabHousekeeping)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.gridLayout_5 = QtWidgets.QGridLayout()
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.hkSingleReadBtn = QtWidgets.QPushButton(self.tabHousekeeping)
        self.hkSingleReadBtn.setObjectName("hkSingleReadBtn")
        self.gridLayout_5.addWidget(self.hkSingleReadBtn, 0, 0, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(288, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_5.addItem(spacerItem2, 0, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.tabHousekeeping)
        self.label_2.setObjectName("label_2")
        self.gridLayout_5.addWidget(self.label_2, 0, 2, 1, 1)
        self.hkPeriodInput = QtWidgets.QSpinBox(self.tabHousekeeping)
        self.hkPeriodInput.setMinimumSize(QtCore.QSize(90, 0))
        self.hkPeriodInput.setProperty("value", 1)
        self.hkPeriodInput.setObjectName("hkPeriodInput")
        self.gridLayout_5.addWidget(self.hkPeriodInput, 0, 3, 1, 1)
        self.hkStartBtn = QtWidgets.QPushButton(self.tabHousekeeping)
        self.hkStartBtn.setObjectName("hkStartBtn")
        self.gridLayout_5.addWidget(self.hkStartBtn, 0, 4, 1, 1)
        self.hkTableWidget = QtWidgets.QTableWidget(self.tabHousekeeping)
        self.hkTableWidget.setObjectName("hkTableWidget")
        self.hkTableWidget.setColumnCount(4)
        self.hkTableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.hkTableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.hkTableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.hkTableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.hkTableWidget.setHorizontalHeaderItem(3, item)
        self.gridLayout_5.addWidget(self.hkTableWidget, 1, 0, 1, 5)
        self.verticalLayout_5.addLayout(self.gridLayout_5)
        self.tabWidget.addTab(self.tabHousekeeping, "")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.tab)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.sciStartDRSBtn = QtWidgets.QPushButton(self.tab)
        self.sciStartDRSBtn.setObjectName("sciStartDRSBtn")
        self.horizontalLayout_3.addWidget(self.sciStartDRSBtn)
        self.sciStopDRSBtn = QtWidgets.QPushButton(self.tab)
        self.sciStopDRSBtn.setObjectName("sciStopDRSBtn")
        self.horizontalLayout_3.addWidget(self.sciStopDRSBtn)
        self.sciTrigDRSBtn = QtWidgets.QPushButton(self.tab)
        self.sciTrigDRSBtn.setObjectName("sciTrigDRSBtn")
        self.horizontalLayout_3.addWidget(self.sciTrigDRSBtn)
        self.sciSingReadBtn = QtWidgets.QPushButton(self.tab)
        self.sciSingReadBtn.setObjectName("sciSingReadBtn")
        self.horizontalLayout_3.addWidget(self.sciSingReadBtn)
        spacerItem3 = QtWidgets.QSpacerItem(368, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem3)
        self.verticalLayout_6.addLayout(self.horizontalLayout_3)
        self.line_2 = QtWidgets.QFrame(self.tab)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.verticalLayout_6.addWidget(self.line_2)
        self.widget_2 = QtWidgets.QWidget(self.tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_2.sizePolicy().hasHeightForWidth())
        self.widget_2.setSizePolicy(sizePolicy)
        self.widget_2.setObjectName("widget_2")
        self.verticalLayout_6.addWidget(self.widget_2)
        self.tabWidget.addTab(self.tab, "")
        self.tab_graphs = QtWidgets.QWidget()
        self.tab_graphs.setObjectName("tab_graphs")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.tab_graphs)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.calStartBtn = QtWidgets.QPushButton(self.tab_graphs)
        self.calStartBtn.setObjectName("calStartBtn")
        self.horizontalLayout_4.addWidget(self.calStartBtn)
        self.calStopBtn = QtWidgets.QPushButton(self.tab_graphs)
        self.calStopBtn.setObjectName("calStopBtn")
        self.horizontalLayout_4.addWidget(self.calStopBtn)
        spacerItem4 = QtWidgets.QSpacerItem(518, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem4)
        self.verticalLayout_4.addLayout(self.horizontalLayout_4)
        self.line = QtWidgets.QFrame(self.tab_graphs)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout_4.addWidget(self.line)
        self.widget = QtWidgets.QWidget(self.tab_graphs)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget.sizePolicy().hasHeightForWidth())
        self.widget.setSizePolicy(sizePolicy)
        self.widget.setObjectName("widget")
        self.verticalLayout_4.addWidget(self.widget)
        self.tabWidget.addTab(self.tab_graphs, "")
        self.verticalLayout.addWidget(self.tabWidget)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1069, 26))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuSettings = QtWidgets.QMenu(self.menubar)
        self.menuSettings.setObjectName("menuSettings")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionIP = QtWidgets.QAction(MainWindow)
        self.actionIP.setObjectName("actionIP")
        self.menuSettings.addAction(self.actionIP)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuSettings.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "HIT DAQ"))
        self.groupBox.setTitle(_translate("MainWindow", "Connection"))
        self.label.setText(_translate("MainWindow", "IP"))
        self.ipEdit.setText(_translate("MainWindow", "192.168.1.117"))
        self.portLabel.setText(_translate("MainWindow", "Port"))
        self.portEdit.setText(_translate("MainWindow", "1002"))
        self.connectButton.setText(_translate("MainWindow", "Connect"))
        self.groupBox_4.setTitle(_translate("MainWindow", "Controls"))
        self.selectFolderBtn.setText(_translate("MainWindow", "Folder"))
        self.folderLabel.setText(_translate("MainWindow", "working directory has not been set!"))
        self.initBtn.setText(_translate("MainWindow", "Initialize"))
        self.readStatBtn.setText(_translate("MainWindow", "Read status"))
        self.lastCmdBtn.setText(_translate("MainWindow", "Last cmd info."))
        self.label_3.setText(_translate("MainWindow", "Log"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_controls), _translate("MainWindow", "Configuration"))
        self.hkSingleReadBtn.setText(_translate("MainWindow", "Single-shot read"))
        self.label_2.setText(_translate("MainWindow", "Updated period (s)"))
        self.hkStartBtn.setText(_translate("MainWindow", "Start"))
        item = self.hkTableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "ID"))
        item = self.hkTableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Name"))
        item = self.hkTableWidget.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Raw Value"))
        item = self.hkTableWidget.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Eng. Value"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabHousekeeping), _translate("MainWindow", "Housekeeping"))
        self.sciStartDRSBtn.setText(_translate("MainWindow", "Start DRS read  "))
        self.sciStopDRSBtn.setText(_translate("MainWindow", "Stop DRS "))
        self.sciTrigDRSBtn.setText(_translate("MainWindow", "trigger DRS"))
        self.sciSingReadBtn.setText(_translate("MainWindow", "Single read per ch."))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Science"))
        self.calStartBtn.setText(_translate("MainWindow", "Start calibration"))
        self.calStopBtn.setText(_translate("MainWindow", "Stop calibration"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_graphs), _translate("MainWindow", "Calibration"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menuSettings.setTitle(_translate("MainWindow", "Settings"))
        self.actionIP.setText(_translate("MainWindow", "IP"))
